# Reference secrets file in parent directory
<<: !include ../secrets.yaml

esphome:
  name: car-heat-remote
  friendly_name: Car Heat Remote
  min_version: 2025.11.0
  name_add_mac_suffix: false

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

# SPI configuration for LoRa
spi:
  mosi_pin: D7  # GPIO13
  miso_pin: D6  # GPIO12
  clk_pin: D5   # GPIO14

# LoRa configuration using native sx127x component
sx127x:
  id: lora_device
  cs_pin: D1    # GPIO5 (SS)
  rst_pin: D2 # GPIO4 (RST)
  dio0_pin: D8  # GPIO15 (DIO0)
  frequency: 915000000  # 915MHz in Hz
  modulation: LORA
  sync_value: 0x34
  spreading_factor: 12
  bandwidth: 125_0kHz
  coding_rate: CR_4_8
  crc_enable: true
  preamble_size: 6  # Minimum required for LoRa
  rx_start: true
  on_packet:
    then:
      - lambda: |-
          ESP_LOGD("lambda", "packet %s", format_hex(x).c_str());
          ESP_LOGD("lambda", "rssi %.2f", rssi);
          ESP_LOGD("lambda", "snr %.2f", snr);


# Home Assistant button to send LoRa message
button:
  - platform: template
    name: "Send LoRa Message"
    id: send_lora_button
    on_press:
      then:
        - sx127x.send_packet:
            data: [0x48, 0x65, 0x6C, 0x6C, 0x6F, 0x20, 0x48, 0x41]  # "Hello HA"

